// <auto-generated />
using Microservices.AspNetCore.ProductService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Microservices.AspNetCore.ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservices.AspNetCore.ProductService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acer Aspire 5 Slim Laptop",
                            Price = 349.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apple MacBook Air",
                            Price = 999.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dell XPS 13",
                            Price = 1199.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 4,
                            Name = "HP Pavilion 15",
                            Price = 549.99m,
                            Stock = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
